name: finance-notebooks
channels:
  - conda-forge
dependencies:
  - bqplot
  - ipython
  - ipykernel
  - ipywidgets
  - jupyter
  - numpy
  - pandas
  - python-dateutil
  - pytz
  - setuptools
  - traitlets
  - traittypes
  - wbformat
  - widgetsnbextension